<template>
  <div class="env-setup-panel">
    <div class="scroll-container">
      <!-- Step 01: Simulation Instance -->
      <StepInstance
        :phase="phase"
        :simulation-id="simulationId"
        :project-data="projectData"
      />

      <!-- Step 02: Generate Agent Profiles -->
      <StepProfiles
        :phase="phase"
        :prepare-progress="prepareProgress"
        :profiles="profiles"
        :expected-total="expectedTotal"
        @select-profile="selectProfile"
      />

      <!-- Step 03: Generate Dual-Platform Simulation Config -->
      <StepConfig :phase="phase" :simulation-config="simulationConfig" />

      <!-- Step 04: Initial Activation Orchestration -->
      <StepOrchestration
        :phase="phase"
        :simulation-config="simulationConfig"
        :profiles="profiles"
      />

      <!-- Step 05: Ready -->
      <div class="step-card" :class="{ 'active': phase === 4 }">
        <div class="card-header">
          <div class="step-info">
            <span class="step-num">05</span>
            <span class="step-title">준비 완료</span>
          </div>
          <div class="step-status">
            <span v-if="phase >= 4" class="badge processing">진행 중</span>
            <span v-else class="badge pending">대기</span>
          </div>
        </div>

        <div class="card-content">
          <p class="api-note">POST /api/simulation/start</p>
          <p class="description">Simulation environment is ready. You can now start running the simulation.</p>
          
          <!-- Simulation rounds config - only shown after config is generated and rounds are calculated -->
          <div v-if="simulationConfig && autoGeneratedRounds" class="rounds-config-section">
            <div class="rounds-header">
              <div class="header-left">
                <span class="section-title">시뮬레이션 라운드 설정</span>
                <span class="section-desc">MiroFish automatically plans simulation of <span class="desc-highlight">{{ simulationConfig?.time_config?.total_simulation_hours || '-' }}</span> real-world hours, each round represents <span class="desc-highlight">{{ simulationConfig?.time_config?.minutes_per_round || '-' }}</span> real-world minutes</span>
              </div>
              <label class="switch-control">
                <input type="checkbox" v-model="useCustomRounds">
                <span class="switch-track"></span>
                <span class="switch-label">커스텀</span>
              </label>
            </div>
            
            <Transition name="fade" mode="out-in">
              <div v-if="useCustomRounds" class="rounds-content custom" key="custom">
                <div class="slider-display">
                  <div class="slider-main-value">
                    <span class="val-num">{{ customMaxRounds }}</span>
                    <span class="val-unit">rounds</span>
                  </div>
                  <div class="slider-meta-info">
                    <span>With 100 agents: estimated ~{{ Math.round(customMaxRounds * 0.6) }} minutes</span>
                  </div>
                </div>

                <div class="range-wrapper">
                  <input 
                    type="range" 
                    v-model.number="customMaxRounds" 
                    min="10" 
                    :max="autoGeneratedRounds"
                    step="5"
                    class="minimal-slider"
                    :style="{ '--percent': ((customMaxRounds - 10) / (autoGeneratedRounds - 10)) * 100 + '%' }"
                  />
                  <div class="range-marks">
                    <span>10</span>
                    <span 
                      class="mark-recommend" 
                      :class="{ active: customMaxRounds === 40 }"
                      @click="customMaxRounds = 40"
                      :style="{ position: 'absolute', left: `calc(${(40 - 10) / (autoGeneratedRounds - 10) * 100}% - 30px)` }"
                    >40 (Recommended)</span>
                    <span>{{ autoGeneratedRounds }}</span>
                  </div>
                </div>
              </div>
              
              <div v-else class="rounds-content auto" key="auto">
                <div class="auto-info-card">
                  <div class="auto-value">
                    <span class="val-num">{{ autoGeneratedRounds }}</span>
                    <span class="val-unit">rounds</span>
                  </div>
                  <div class="auto-content">
                    <div class="auto-meta-row">
                      <span class="duration-badge">
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                          <circle cx="12" cy="12" r="10"></circle>
                          <polyline points="12 6 12 12 16 14"></polyline>
                        </svg>
                        With 100 agents: estimated {{ Math.round(autoGeneratedRounds * 0.6) }} minutes
                      </span>
                    </div>
                    <div class="auto-desc">
                      <p class="highlight-tip" @click="useCustomRounds = true">For first-time runs, we strongly recommend switching to ‘Custom Mode’ to reduce simulation rounds for a quick preview and lower error risk ➝</p>
                    </div>
                  </div>
                </div>
              </div>
            </Transition>
          </div>

          <div class="action-group dual">
            <button 
              class="action-btn secondary"
              @click="$emit('go-back')"
            >
              ← Back to Graph Build
            </button>
            <button 
              class="action-btn primary"
              :disabled="phase < 4"
              @click="handleStartSimulation"
            >
              Start Dual-World Parallel Simulation ➝
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Profile Detail Modal -->
    <ProfileDetailModal
      :profile="selectedProfile"
      @close="selectedProfile = null"
    />

    <!-- Bottom Info / Logs -->
    <div class="system-logs">
      <div class="log-header">
        <span class="log-title">시스템 대시보드</span>
        <span class="log-id">{{ simulationId || 'NO_SIMULATION' }}</span>
      </div>
      <div class="log-content" ref="logContent">
        <div class="log-line" v-for="(log, idx) in systemLogs" :key="idx">
          <span class="log-time">{{ log.time }}</span>
          <span class="log-msg">{{ log.msg }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, toRef, watch, onMounted, onBeforeUnmount, onUnmounted, nextTick } from 'vue'
import { usePrepareSimulation } from '../composables/usePrepareSimulation'
import ProfileDetailModal from './Step2/ProfileDetailModal.vue'
import StepInstance from './Step2/StepInstance.vue'
import StepProfiles from './Step2/StepProfiles.vue'
import StepConfig from './Step2/StepConfig.vue'
import StepOrchestration from './Step2/StepOrchestration.vue'

const props = defineProps({
  simulationId: String,  // Passed from parent component
  projectData: Object,
  graphData: Object,
  systemLogs: Array
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

// 시뮬레이션 준비 플로우 (status / profiles / config 폴링 + orchestration)
const {
  phase,
  prepareProgress,
  currentStage,
  progressMessage,
  profiles,
  entityTypes,
  expectedTotal,
  simulationConfig,
  autoGeneratedRounds,
  startPrepareSimulation,
  clearAllTimers,
} = usePrepareSimulation({
  simulationId: toRef(props, 'simulationId'),
  addLog: (msg) => emit('add-log', msg),
  updateStatus: (status) => emit('update-status', status),
})

// UI-only state
const selectedProfile = ref(null)
const useCustomRounds = ref(false)
const customMaxRounds = ref(40)

const handleStartSimulation = () => {
  const params = {}
  if (useCustomRounds.value) {
    params.maxRounds = customMaxRounds.value
    emit('add-log', `Starting simulation, custom rounds: ${customMaxRounds.value}`)
  } else {
    emit('add-log', `Starting simulation, using auto-configured rounds: ${autoGeneratedRounds.value}`)
  }
  emit('next-step', params)
}

const selectProfile = (profile) => { selectedProfile.value = profile }

// Scroll log to bottom on new entries
const logContent = ref(null)
watch(() => props.systemLogs?.length, () => {
  nextTick(() => {
    if (logContent.value) {
      logContent.value.scrollTop = logContent.value.scrollHeight
    }
  })
})

onMounted(() => {
  if (props.simulationId) {
    emit('add-log', 'Step2 Environment Setup Initialization')
    startPrepareSimulation()
  }
})

onBeforeUnmount(clearAllTimers)
onUnmounted(clearAllTimers)
</script>

<style scoped src="./Step2EnvSetup.styles.css"></style>
