<template>
  <div class="env-setup-panel">
    <div class="scroll-container">
      <!-- Step 01: Simulation Instance -->
      <StepInstance
        :phase="phase"
        :simulation-id="simulationId"
        :project-data="projectData"
      />

      <!-- Step 02: Generate Agent Profiles -->
      <StepProfiles
        :phase="phase"
        :prepare-progress="prepareProgress"
        :profiles="profiles"
        :expected-total="expectedTotal"
        @select-profile="selectProfile"
      />

      <!-- Step 03: Generate Dual-Platform Simulation Config -->
      <StepConfig :phase="phase" :simulation-config="simulationConfig" />

      <!-- Step 04: Initial Activation Orchestration -->
      <StepOrchestration
        :phase="phase"
        :simulation-config="simulationConfig"
        :profiles="profiles"
      />

      <!-- Step 05: Ready -->
      <StepReady
        :phase="phase"
        :simulation-config="simulationConfig"
        :auto-generated-rounds="autoGeneratedRounds"
        @go-back="$emit('go-back')"
        @start="handleStart"
      />
    </div>

    <!-- Profile Detail Modal -->
    <ProfileDetailModal
      :profile="selectedProfile"
      @close="selectedProfile = null"
    />

    <!-- Bottom Info / Logs -->
    <div class="system-logs">
      <div class="log-header">
        <span class="log-title">시스템 대시보드</span>
        <span class="log-id">{{ simulationId || 'NO_SIMULATION' }}</span>
      </div>
      <div class="log-content" ref="logContent">
        <div class="log-line" v-for="(log, idx) in systemLogs" :key="idx">
          <span class="log-time">{{ log.time }}</span>
          <span class="log-msg">{{ log.msg }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, toRef, watch, onMounted, onBeforeUnmount, onUnmounted, nextTick } from 'vue'
import { usePrepareSimulation } from '../composables/usePrepareSimulation'
import ProfileDetailModal from './Step2/ProfileDetailModal.vue'
import StepInstance from './Step2/StepInstance.vue'
import StepProfiles from './Step2/StepProfiles.vue'
import StepConfig from './Step2/StepConfig.vue'
import StepOrchestration from './Step2/StepOrchestration.vue'
import StepReady from './Step2/StepReady.vue'

const props = defineProps({
  simulationId: String,  // Passed from parent component
  projectData: Object,
  graphData: Object,
  systemLogs: Array
})

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

// 시뮬레이션 준비 플로우 (status / profiles / config 폴링 + orchestration)
const {
  phase,
  prepareProgress,
  currentStage,
  progressMessage,
  profiles,
  entityTypes,
  expectedTotal,
  simulationConfig,
  autoGeneratedRounds,
  startPrepareSimulation,
  clearAllTimers,
} = usePrepareSimulation({
  simulationId: toRef(props, 'simulationId'),
  addLog: (msg) => emit('add-log', msg),
  updateStatus: (status) => emit('update-status', status),
})

// UI-only state
const selectedProfile = ref(null)

const handleStart = ({ isCustom, maxRounds }) => {
  const params = isCustom ? { maxRounds } : {}
  const logSuffix = isCustom
    ? `custom rounds: ${maxRounds}`
    : `using auto-configured rounds: ${maxRounds}`
  emit('add-log', `Starting simulation, ${logSuffix}`)
  emit('next-step', params)
}

const selectProfile = (profile) => { selectedProfile.value = profile }

// Scroll log to bottom on new entries
const logContent = ref(null)
watch(() => props.systemLogs?.length, () => {
  nextTick(() => {
    if (logContent.value) {
      logContent.value.scrollTop = logContent.value.scrollHeight
    }
  })
})

onMounted(() => {
  if (props.simulationId) {
    emit('add-log', 'Step2 Environment Setup Initialization')
    startPrepareSimulation()
  }
})

onBeforeUnmount(clearAllTimers)
onUnmounted(clearAllTimers)
</script>

<style scoped src="./Step2EnvSetup.styles.css"></style>
