<template>
  <div class="step-card" :class="{ 'active': phase === 4 }">
    <div class="card-header">
      <div class="step-info">
        <span class="step-num">05</span>
        <span class="step-title">준비 완료</span>
      </div>
      <div class="step-status">
        <span v-if="phase >= 4" class="badge processing">진행 중</span>
        <span v-else class="badge pending">대기</span>
      </div>
    </div>

    <div class="card-content">
      <p class="api-note">POST /api/simulation/start</p>
      <p class="description">Simulation environment is ready. You can now start running the simulation.</p>

      <!-- Simulation rounds config - only shown after config is generated and rounds are calculated -->
      <div v-if="simulationConfig && autoGeneratedRounds" class="rounds-config-section">
        <div class="rounds-header">
          <div class="header-left">
            <span class="section-title">시뮬레이션 라운드 설정</span>
            <span class="section-desc">MiroFish automatically plans simulation of <span class="desc-highlight">{{ simulationConfig?.time_config?.total_simulation_hours || '-' }}</span> real-world hours, each round represents <span class="desc-highlight">{{ simulationConfig?.time_config?.minutes_per_round || '-' }}</span> real-world minutes</span>
          </div>
          <label class="switch-control">
            <input type="checkbox" v-model="useCustomRounds">
            <span class="switch-track"></span>
            <span class="switch-label">커스텀</span>
          </label>
        </div>

        <Transition name="fade" mode="out-in">
          <div v-if="useCustomRounds" class="rounds-content custom" key="custom">
            <div class="slider-display">
              <div class="slider-main-value">
                <span class="val-num">{{ customMaxRounds }}</span>
                <span class="val-unit">rounds</span>
              </div>
              <div class="slider-meta-info">
                <span>With 100 agents: estimated ~{{ Math.round(customMaxRounds * 0.6) }} minutes</span>
              </div>
            </div>

            <div class="range-wrapper">
              <input
                type="range"
                v-model.number="customMaxRounds"
                min="10"
                :max="autoGeneratedRounds"
                step="5"
                class="minimal-slider"
                :style="{ '--percent': ((customMaxRounds - 10) / (autoGeneratedRounds - 10)) * 100 + '%' }"
              />
              <div class="range-marks">
                <span>10</span>
                <span
                  class="mark-recommend"
                  :class="{ active: customMaxRounds === 40 }"
                  @click="customMaxRounds = 40"
                  :style="{ position: 'absolute', left: `calc(${(40 - 10) / (autoGeneratedRounds - 10) * 100}% - 30px)` }"
                >40 (Recommended)</span>
                <span>{{ autoGeneratedRounds }}</span>
              </div>
            </div>
          </div>

          <div v-else class="rounds-content auto" key="auto">
            <div class="auto-info-card">
              <div class="auto-value">
                <span class="val-num">{{ autoGeneratedRounds }}</span>
                <span class="val-unit">rounds</span>
              </div>
              <div class="auto-content">
                <div class="auto-meta-row">
                  <span class="duration-badge">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                      <circle cx="12" cy="12" r="10"></circle>
                      <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    With 100 agents: estimated {{ Math.round(autoGeneratedRounds * 0.6) }} minutes
                  </span>
                </div>
                <div class="auto-desc">
                  <p class="highlight-tip" @click="useCustomRounds = true">For first-time runs, we strongly recommend switching to ‘Custom Mode’ to reduce simulation rounds for a quick preview and lower error risk ➝</p>
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>

      <div class="action-group dual">
        <button
          class="action-btn secondary"
          @click="$emit('go-back')"
        >
          ← Back to Graph Build
        </button>
        <button
          class="action-btn primary"
          :disabled="phase < 4"
          @click="onStart"
        >
          Start Dual-World Parallel Simulation ➝
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  phase: { type: Number, required: true },
  simulationConfig: { type: Object, default: null },
  autoGeneratedRounds: { type: Number, default: 0 },
})

const emit = defineEmits(['go-back', 'start'])

const useCustomRounds = ref(false)
const customMaxRounds = ref(40)

const onStart = () => {
  emit('start', {
    isCustom: useCustomRounds.value,
    maxRounds: useCustomRounds.value ? customMaxRounds.value : props.autoGeneratedRounds,
  })
}
</script>

<style scoped src="./_step-framework.css"></style>
<style scoped>
/* Action Section */
.action-section {
  margin-top: 16px;
}

.action-btn {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px;
  font-size: 14px;
  font-weight: 600;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.action-btn.primary {
  background: #000;
  color: #FFF;
}

.action-btn.primary:hover:not(:disabled) {
  opacity: 0.8;
}

.action-btn.secondary {
  background: #F5F5F5;
  color: #333;
}

.action-btn.secondary:hover:not(:disabled) {
  background: #E5E5E5;
}

.action-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.action-group {
  display: flex;
  gap: 12px;
  margin-top: 16px;
}

.action-group.dual {
  display: grid;
  grid-template-columns: 1fr 1fr;
}

.action-group.dual .action-btn {
  width: 100%;
}

/* Simulation Rounds Config Styles */
.rounds-config-section {
  margin: 24px 0;
  padding-top: 24px;
  border-top: 1px solid #EAEAEA;
}

.rounds-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.header-left {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.section-title {
  font-size: 14px;
  font-weight: 600;
  color: #1E293B;
}

.section-desc {
  font-size: 12px;
  color: #94A3B8;
}

.desc-highlight {
  font-family: 'JetBrains Mono', monospace;
  font-weight: 600;
  color: #1E293B;
  background: #F1F5F9;
  padding: 1px 6px;
  border-radius: 4px;
  margin: 0 2px;
}

/* Switch Control */
.switch-control {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  padding: 4px 8px 4px 4px;
  border-radius: 20px;
  transition: background 0.2s;
}

.switch-control:hover {
  background: #F8FAFC;
}

.switch-control input {
  display: none;
}

.switch-track {
  width: 36px;
  height: 20px;
  background: #E2E8F0;
  border-radius: 10px;
  position: relative;
  transition: all 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
}

.switch-track::after {
  content: '';
  position: absolute;
  left: 2px;
  top: 2px;
  width: 16px;
  height: 16px;
  background: #FFF;
  border-radius: 50%;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  transition: transform 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
}

.switch-control input:checked + .switch-track {
  background: #000;
}

.switch-control input:checked + .switch-track::after {
  transform: translateX(16px);
}

.switch-label {
  font-size: 12px;
  font-weight: 500;
  color: #64748B;
}

.switch-control input:checked ~ .switch-label {
  color: #1E293B;
}

/* Slider Content */
.rounds-content {
  animation: fadeIn 0.3s ease;
}

.slider-display {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  margin-bottom: 16px;
}

.slider-main-value {
  display: flex;
  align-items: baseline;
  gap: 4px;
}

.val-num {
  font-family: 'JetBrains Mono', monospace;
  font-size: 24px;
  font-weight: 700;
  color: #000;
}

.val-unit {
  font-size: 12px;
  color: #666;
  font-weight: 500;
}

.slider-meta-info {
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px;
  color: #64748B;
  background: #F1F5F9;
  padding: 4px 8px;
  border-radius: 4px;
}

.range-wrapper {
  position: relative;
  padding: 0 2px;
}

.minimal-slider {
  -webkit-appearance: none;
  width: 100%;
  height: 4px;
  background: #E2E8F0;
  border-radius: 2px;
  outline: none;
  background-image: linear-gradient(#000, #000);
  background-size: var(--percent, 0%) 100%;
  background-repeat: no-repeat;
  cursor: pointer;
}

.minimal-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #FFF;
  border: 2px solid #000;
  cursor: pointer;
  box-shadow: 0 1px 4px rgba(0,0,0,0.1);
  transition: transform 0.1s;
  margin-top: -6px;
}

.minimal-slider::-webkit-slider-thumb:hover {
  transform: scale(1.1);
}

.minimal-slider::-webkit-slider-runnable-track {
  height: 4px;
  border-radius: 2px;
}

.range-marks {
  display: flex;
  justify-content: space-between;
  margin-top: 8px;
  font-family: 'JetBrains Mono', monospace;
  font-size: 10px;
  color: #94A3B8;
  position: relative;
}

.mark-recommend {
  cursor: pointer;
  transition: color 0.2s;
  position: relative;
}

.mark-recommend:hover {
  color: #000;
}

.mark-recommend.active {
  color: #000;
  font-weight: 600;
}

.mark-recommend::after {
  content: '';
  position: absolute;
  top: -12px;
  left: 50%;
  transform: translateX(-50%);
  width: 1px;
  height: 4px;
  background: #CBD5E1;
}

/* Auto Info */
.auto-info-card {
  display: flex;
  align-items: center;
  gap: 24px;
  background: #F8FAFC;
  padding: 16px 20px;
  border-radius: 8px;
}

.auto-value {
  display: flex;
  flex-direction: row;
  align-items: baseline;
  gap: 4px;
  padding-right: 24px;
  border-right: 1px solid #E2E8F0;
}

.auto-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 8px;
  justify-content: center;
}

.auto-meta-row {
  display: flex;
  align-items: center;
}

.duration-badge {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-family: 'JetBrains Mono', monospace;
  font-size: 11px;
  font-weight: 500;
  color: #64748B;
  background: #FFFFFF;
  border: 1px solid #E2E8F0;
  padding: 3px 8px;
  border-radius: 6px;
  box-shadow: 0 1px 2px rgba(0,0,0,0.02);
}

.auto-desc {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.auto-desc p {
  margin: 0;
  font-size: 13px;
  color: #64748B;
  line-height: 1.5;
}

.highlight-tip {
  margin-top: 4px !important;
  font-size: 12px !important;
  color: #000 !important;
  font-weight: 500;
  cursor: pointer;
}

.highlight-tip:hover {
  text-decoration: underline;
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(4px); }
  to { opacity: 1; transform: translateY(0); }
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
