/**
 * Step2EnvSetup 의 시뮬레이션 준비 플로우 (TODOS #5).
 *
 * 3개 폴링 (status / profiles / config) + orchestration 을 한 곳에 모음.
 * SFC 는 props/UI handler 만 담당.
 *
 * 폴링 주기:
 * - status:    2000ms — prepare task 진행률
 * - profiles:  3000ms — Agent profile 실시간 스트림
 * - config:    2000ms — simulation config 생성 단계
 *
 * Phase 의미:
 *   0 = initializing
 *   1 = generating profiles
 *   2 = generating config
 *   4 = complete
 */
import { ref, computed, watch } from 'vue'
import {
  prepareSimulation,
  getPrepareStatus,
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime,
} from '../api/simulation'
import { showToast } from '../utils/toast'

export function usePrepareSimulation({ simulationId, addLog, updateStatus }) {
  // ── State ──────────────────────────────────────────────────────────────
  const phase = ref(0)
  const taskId = ref(null)
  const prepareProgress = ref(0)
  const currentStage = ref('')
  const progressMessage = ref('')
  const profiles = ref([])
  const entityTypes = ref([])
  const expectedTotal = ref(null)
  const simulationConfig = ref(null)

  // ── 로그 중복 제거용 ───────────────────────────────────────────────────
  let lastLoggedMessage = ''
  let lastLoggedProfileCount = 0
  let lastLoggedConfigStage = ''

  // ── Timers ─────────────────────────────────────────────────────────────
  let pollTimer = null
  let profilesTimer = null
  let configTimer = null

  // currentStage 가 바뀌면 phase + config polling 트리거
  watch(currentStage, (newStage) => {
    if (newStage === 'Generating Agent Profiles' || newStage === 'generating_profiles') {
      phase.value = 1
    } else if (newStage === 'Generating Simulation Config' || newStage === 'generating_config') {
      phase.value = 2
      if (!configTimer) {
        addLog('Starting dual-platform simulation config generation...')
        startConfigPolling()
      }
    } else if (newStage === 'Preparing Simulation Scripts' || newStage === 'copying_scripts') {
      phase.value = 2
    }
  })

  const autoGeneratedRounds = computed(() => {
    const tc = simulationConfig.value?.time_config
    if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return null
    const calculated = Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round)
    return Math.max(calculated, 40)
  })

  // ── Status polling ─────────────────────────────────────────────────────
  const startPolling = () => {
    pollTimer = setInterval(pollPrepareStatus, 2000)
  }
  const stopPolling = () => {
    if (pollTimer) {
      clearInterval(pollTimer)
      pollTimer = null
    }
  }

  const pollPrepareStatus = async () => {
    if (!taskId.value && !simulationId.value) return

    try {
      const res = await getPrepareStatus({
        task_id: taskId.value,
        simulation_id: simulationId.value,
      })
      if (!res.success || !res.data) return

      const data = res.data
      prepareProgress.value = data.progress || 0
      progressMessage.value = data.message || ''

      if (data.progress_detail) {
        currentStage.value = data.progress_detail.current_stage_name || ''
        const detail = data.progress_detail
        const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`
        if (logKey !== lastLoggedMessage && detail.item_description) {
          lastLoggedMessage = logKey
          const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`
          if (detail.total_items > 0) {
            addLog(`${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`)
          } else {
            addLog(`${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`)
          }
        }
      } else if (data.message) {
        const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/)
        if (match) currentStage.value = match[3].trim()
        if (data.message !== lastLoggedMessage) {
          lastLoggedMessage = data.message
          addLog(data.message)
        }
      }

      if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
        addLog('✓ Preparation completed')
        stopPolling()
        stopProfilesPolling()
        await loadPreparedData()
      } else if (data.status === 'failed') {
        addLog(`✗ Preparation failed: ${data.error || 'Unknown error'}`)
        stopPolling()
        stopProfilesPolling()
      }
    } catch (err) {
      console.warn('Polling status failed:', err)
    }
  }

  // ── Profiles polling ───────────────────────────────────────────────────
  const startProfilesPolling = () => {
    profilesTimer = setInterval(fetchProfilesRealtime, 3000)
  }
  const stopProfilesPolling = () => {
    if (profilesTimer) {
      clearInterval(profilesTimer)
      profilesTimer = null
    }
  }

  const fetchProfilesRealtime = async () => {
    if (!simulationId.value) return

    try {
      const res = await getSimulationProfilesRealtime(simulationId.value, 'reddit')
      if (!res.success || !res.data) return

      profiles.value = res.data.profiles || []
      if (res.data.total_expected) expectedTotal.value = res.data.total_expected

      const types = new Set()
      profiles.value.forEach(p => p.entity_type && types.add(p.entity_type))
      entityTypes.value = Array.from(types)

      const currentCount = profiles.value.length
      if (currentCount > 0 && currentCount !== lastLoggedProfileCount) {
        lastLoggedProfileCount = currentCount
        const total = expectedTotal.value || '?'
        const latest = profiles.value[currentCount - 1]
        const profileName = latest?.name || latest?.username || `Agent_${currentCount}`
        if (currentCount === 1) addLog('Starting Agent profile generation...')
        addLog(`→ Agent profile ${currentCount}/${total}: ${profileName} (${latest?.profession || 'Unknown profession'})`)
        if (expectedTotal.value && currentCount >= expectedTotal.value) {
          addLog(`✓ All ${currentCount} Agent profiles generated`)
        }
      }
    } catch (err) {
      console.warn('Failed to fetch profiles:', err)
    }
  }

  // ── Config polling ─────────────────────────────────────────────────────
  const startConfigPolling = () => {
    configTimer = setInterval(fetchConfigRealtime, 2000)
  }
  const stopConfigPolling = () => {
    if (configTimer) {
      clearInterval(configTimer)
      configTimer = null
    }
  }

  const fetchConfigRealtime = async () => {
    if (!simulationId.value) return

    try {
      const res = await getSimulationConfigRealtime(simulationId.value)
      if (!res.success || !res.data) return
      const data = res.data

      if (data.generation_stage && data.generation_stage !== lastLoggedConfigStage) {
        lastLoggedConfigStage = data.generation_stage
        if (data.generation_stage === 'generating_profiles') {
          addLog('Generating Agent profile config...')
        } else if (data.generation_stage === 'generating_config') {
          addLog('Calling LLM to generate simulation config parameters...')
        }
      }

      if (data.config_generated && data.config) {
        simulationConfig.value = data.config
        addLog('✓ Simulation config generation complete')

        if (data.summary) {
          addLog(`  ├─ Agent count: ${data.summary.total_agents}`)
          addLog(`  ├─ Simulation duration: ${data.summary.simulation_hours} hours`)
          addLog(`  ├─ Initial posts: ${data.summary.initial_posts_count}`)
          addLog(`  ├─ Trending topics: ${data.summary.hot_topics_count}`)
          addLog(`  └─ Platform config: Twitter ${data.summary.has_twitter_config ? '✓' : '✗'}, Reddit ${data.summary.has_reddit_config ? '✓' : '✗'}`)
        }

        if (data.config.time_config) {
          const tc = data.config.time_config
          addLog(`Time config: ${tc.minutes_per_round} min/round, ${Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round)} total rounds`)
        }

        if (data.config.event_config?.narrative_direction) {
          const narrative = data.config.event_config.narrative_direction
          addLog(`Narrative direction: ${narrative.length > 50 ? narrative.substring(0, 50) + '...' : narrative}`)
        }

        stopConfigPolling()
        phase.value = 4
        addLog('✓ Environment setup complete, ready to start simulation')
        updateStatus('completed')
      }
    } catch (err) {
      console.warn('Failed to fetch config:', err)
    }
  }

  // ── Orchestration ──────────────────────────────────────────────────────
  const startPrepareSimulation = async () => {
    if (!simulationId.value) {
      addLog('Error: missing simulationId')
      updateStatus('error')
      return
    }

    phase.value = 1
    addLog(`Simulation instance created: ${simulationId.value}`)
    addLog('Preparing simulation environment...')
    updateStatus('processing')

    try {
      const res = await prepareSimulation({
        simulation_id: simulationId.value,
        use_llm_for_profiles: true,
        parallel_profile_count: 5,
      })

      if (res.success && res.data) {
        if (res.data.already_prepared) {
          addLog('Detected completed preparation work, using directly')
          await loadPreparedData()
          return
        }

        taskId.value = res.data.task_id
        addLog('Preparation task started')
        addLog(`  └─ Task ID: ${res.data.task_id}`)

        if (res.data.expected_entities_count) {
          expectedTotal.value = res.data.expected_entities_count
          addLog(`Read ${res.data.expected_entities_count} entities from Zep graph`)
          if (res.data.entity_types?.length > 0) {
            addLog(`  └─ Entity types: ${res.data.entity_types.join(', ')}`)
          }
        }

        addLog('Starting to poll preparation progress...')
        startPolling()
        startProfilesPolling()
      } else {
        addLog(`Preparation failed: ${res.error || 'Unknown error'}`)
        showToast(`시뮬레이션 준비에 실패했습니다: ${res.error || '알 수 없는 오류'}`, 'error')
        updateStatus('error')
      }
    } catch (err) {
      addLog(`Preparation exception: ${err.message}`)
      showToast(`시뮬레이션 준비 중 오류가 발생했습니다: ${err.message}`, 'error')
      updateStatus('error')
    }
  }

  const loadPreparedData = async () => {
    phase.value = 2
    addLog('Loading existing config data...')

    await fetchProfilesRealtime()
    addLog(`Loaded ${profiles.value.length} Agent profiles`)

    try {
      const res = await getSimulationConfigRealtime(simulationId.value)
      if (res.success && res.data) {
        if (res.data.config_generated && res.data.config) {
          simulationConfig.value = res.data.config
          addLog('✓ Simulation config loaded successfully')

          if (res.data.summary) {
            addLog(`  ├─ Agent count: ${res.data.summary.total_agents}`)
            addLog(`  ├─ Simulation duration: ${res.data.summary.simulation_hours} hours`)
            addLog(`  └─ Initial posts: ${res.data.summary.initial_posts_count}`)
          }

          addLog('✓ Environment setup complete, ready to start simulation')
          phase.value = 4
          updateStatus('completed')
        } else {
          addLog('Config generating, starting poll wait...')
          startConfigPolling()
        }
      }
    } catch (err) {
      addLog(`Failed to load config: ${err.message}`)
      updateStatus('error')
    }
  }

  const clearAllTimers = () => {
    stopPolling()
    stopProfilesPolling()
    stopConfigPolling()
  }

  return {
    // state
    phase,
    prepareProgress,
    currentStage,
    progressMessage,
    profiles,
    entityTypes,
    expectedTotal,
    simulationConfig,
    autoGeneratedRounds,
    // actions
    startPrepareSimulation,
    clearAllTimers,
  }
}
